schema = 3

[mod]
  [mod."cloud.google.com/go"]
    version = "v0.121.6"
    hash = "sha256-WhK5XwWOKB6sIxA5EAbEGqec3AGpx337a561gnRO3oQ="
  [mod."cloud.google.com/go/auth"]
    version = "v0.17.0"
    hash = "sha256-AVNd+Ax9X5J053O6mXKDiOh75DEPXjS5WPmJFITKMrE="
  [mod."cloud.google.com/go/auth/oauth2adapt"]
    version = "v0.2.8"
    hash = "sha256-GoXFqAbp1WO1tDj07PF5EyxDYvCBP0l0qwxY2oV2hfc="
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.9.0"
    hash = "sha256-VFqQwLJKyH1zReR/XtygEHP5UkI01T9BHEL0hvXtauo="
  [mod."dario.cat/mergo"]
    version = "v1.0.2"
    hash = "sha256-p6jdiHlLEfZES8vJnDywG4aVzIe16p0CU6iglglIweA="
  [mod."github.com/Azure/azure-sdk-for-go/sdk/azcore"]
    version = "v1.19.1"
    hash = "sha256-+cax/D2o8biQuuZkPTwTRECDPE3Ci25il9iVBcOiLC4="
  [mod."github.com/Azure/azure-sdk-for-go/sdk/internal"]
    version = "v1.11.2"
    hash = "sha256-O4Vo6D/fus3Qhs/Te644+jh2LfiG5PpiMkW0YWIbLCs="
  [mod."github.com/KyleBanks/depth"]
    version = "v1.2.1"
    hash = "sha256-czR52MfeKA2FdStXCebTMQRKT8jaWQcbV214O3j49qU="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.2"
    hash = "sha256-tVNWDUMILZbJvarcl/E7tpSnkn7urqgSHa2Eaka5vSU="
  [mod."github.com/ProtonMail/go-crypto"]
    version = "v1.3.0"
    hash = "sha256-TUG+C4MyeWglOmiwiW2/NUVurFHXLgEPRd3X9uQ1NGI="
  [mod."github.com/andybalholm/cascadia"]
    version = "v1.3.3"
    hash = "sha256-jv7ZshpSd7FZzKKN6hqlUgiR8C3y85zNIS/hq7g76Ho="
  [mod."github.com/anthropics/anthropic-sdk-go"]
    version = "v1.19.0"
    hash = "sha256-ubYeau5XL0tx4c/79L58rzJGOdOWs9z6WQOtN6mpgxw="
  [mod."github.com/araddon/dateparse"]
    version = "v0.0.0-20210429162001-6b43995a97de"
    hash = "sha256-UuX84naeRGMsFOgIgRoBHG5sNy1CzBkWPKmd6VbLwFw="
  [mod."github.com/atotto/clipboard"]
    version = "v0.1.4"
    hash = "sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk="
  [mod."github.com/aws/aws-sdk-go-v2"]
    version = "v1.41.0"
    hash = "sha256-cTFa0GPh/PU5mA1ZEd2n1OfY4MYJlRjiKMEt7p1jjCc="
  [mod."github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream"]
    version = "v1.7.4"
    hash = "sha256-ZY/Jn1p0IgDe8MONhp0RFHZmRgTBZZ5ddqXlNWEo7Ys="
  [mod."github.com/aws/aws-sdk-go-v2/config"]
    version = "v1.32.6"
    hash = "sha256-FKoxYfQdCL/3LbiVzRRWZvnoshmIPiUvEeSW71vscbg="
  [mod."github.com/aws/aws-sdk-go-v2/credentials"]
    version = "v1.19.6"
    hash = "sha256-Z8lkOvb+EbggC05jExwt8EH07v3W1bG2+gFAAYE/JSU="
  [mod."github.com/aws/aws-sdk-go-v2/feature/ec2/imds"]
    version = "v1.18.16"
    hash = "sha256-UcwhhFCPfs7oDe5KZQtjFQJwZZ9PccADm2S2kPxmL1I="
  [mod."github.com/aws/aws-sdk-go-v2/internal/configsources"]
    version = "v1.4.16"
    hash = "sha256-V8KSxmnku2liBxa0fWI7zK0vTbdsyk1gxlYgsxp0t+g="
  [mod."github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"]
    version = "v2.7.16"
    hash = "sha256-2FIb59SM2YKzwpXGfbRwFyPug/u5LHJHu4lu+a6WG8g="
  [mod."github.com/aws/aws-sdk-go-v2/internal/ini"]
    version = "v1.8.4"
    hash = "sha256-okyFQwcEqbwKwkGK5xp/VYE0fGg9cqG6AuLijIuf5xg="
  [mod."github.com/aws/aws-sdk-go-v2/service/bedrock"]
    version = "v1.53.0"
    hash = "sha256-DcGcNezcQKUrjpVIrWqwkIGa3phz4Uem70Cs4zuYpyU="
  [mod."github.com/aws/aws-sdk-go-v2/service/bedrockruntime"]
    version = "v1.47.1"
    hash = "sha256-pbIEHn7I6t9W+AkBtZQHHSb4YxVGeAZq7lTik5lys9g="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding"]
    version = "v1.13.4"
    hash = "sha256-Rm6czqOnOULP080D97WQQSqkBhmN6ei1qZaTa51SRj8="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"]
    version = "v1.13.16"
    hash = "sha256-ACVw9W+nGqp0K6Rq9yKhtrC3Yr/oLpRbz0kJbNDwvUM="
  [mod."github.com/aws/aws-sdk-go-v2/service/signin"]
    version = "v1.0.4"
    hash = "sha256-2LEq//DhBh+waRkE6vmt86pjKQN/dCbn/qrhAdQhrVg="
  [mod."github.com/aws/aws-sdk-go-v2/service/sso"]
    version = "v1.30.8"
    hash = "sha256-bYm2waTtLxzg0f82gBitJpoC9Q2jbdqoaNYbd88z3tA="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssooidc"]
    version = "v1.35.12"
    hash = "sha256-m2hboee3VLOrs6zZqMfWO9Ojpc2s4Ei1VCA/m9tf4BU="
  [mod."github.com/aws/aws-sdk-go-v2/service/sts"]
    version = "v1.41.5"
    hash = "sha256-/dF+PVj7+JIm+UxsjXTFV8Q4g2hNwoURbsHHgsmZuhk="
  [mod."github.com/aws/smithy-go"]
    version = "v1.24.0"
    hash = "sha256-ZPFhf2Yv3BQpUn3cN4wSnoO7uBki8oCisZxL6F09nnE="
  [mod."github.com/bytedance/gopkg"]
    version = "v0.1.3"
    hash = "sha256-GyUbPfn41y/mgj0cQOa4tm+aj70C2K50VBZxZc/tcZE="
  [mod."github.com/bytedance/sonic"]
    version = "v1.14.2"
    hash = "sha256-S6EGwzt3TaTUjU1SdtorTdAq3xwROzSGZT6ynfLNq8o="
  [mod."github.com/bytedance/sonic/loader"]
    version = "v0.4.0"
    hash = "sha256-Hc2bB9nLEFhyipIVHKnJmi6WMoWPCe0REK3bmQThO4A="
  [mod."github.com/cloudflare/circl"]
    version = "v1.6.1"
    hash = "sha256-Dc69V12eIFnJoUNmwg6VKXHfAMijbAeEVSDe8AiOaLo="
  [mod."github.com/cloudwego/base64x"]
    version = "v0.1.6"
    hash = "sha256-VzYJsGubsDk3FAMH6e0Xk0Cl4HtUFHHmWkVASUYidsI="
  [mod."github.com/coder/websocket"]
    version = "v1.8.13"
    hash = "sha256-NbF0aPhy8YR3jRM6LMMQTtkeGTFba0eIBPAUsqI9KOk="
  [mod."github.com/cyphar/filepath-securejoin"]
    version = "v0.4.1"
    hash = "sha256-NOV6MfbkcQbfhNmfADQw2SJmZ6q1nw0wwg8Pm2tf2DM="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/emirpasic/gods"]
    version = "v1.18.1"
    hash = "sha256-hGDKddjLj+5dn2woHtXKUdd49/3xdsqnhx7VEdCu1m4="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.12"
    hash = "sha256-vY2g58yUrkT//8fttRKhS9rbg89YSae/BzOARS5uH30="
  [mod."github.com/gin-contrib/sse"]
    version = "v1.1.0"
    hash = "sha256-2VP6zHEsPi0u2ZYpOTcLulwj1Gsmb6oA19qcP2/AzVM="
  [mod."github.com/gin-gonic/gin"]
    version = "v1.11.0"
    hash = "sha256-tFP0u7TZyB1V8b1mdnTWMrfdcwzf9yO86RZr026K8Ao="
  [mod."github.com/go-git/gcfg"]
    version = "v1.5.1-0.20230307220236-3a3c6141e376"
    hash = "sha256-f4k0gSYuo0/q3WOoTxl2eFaj7WZpdz29ih6CKc8Ude8="
  [mod."github.com/go-git/go-billy/v5"]
    version = "v5.6.2"
    hash = "sha256-VgbxcLkHjiSyRIfKS7E9Sn8OynCrMGUDkwFz6K2TVL4="
  [mod."github.com/go-git/go-git/v5"]
    version = "v5.16.4"
    hash = "sha256-y8pzypv2vAhaDRQbL1dhfvD+2s9jPcqg/EALko89gkI="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.22.4"
    hash = "sha256-V76k+oQUyqkWcpa64bOirteoCfdn1Xm9TLH0/7W4Uxc="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.21.4"
    hash = "sha256-R+Q/MOSRTMiOaZutRmjv/qwbU9/cUWN59Hwr2LgDz2U="
  [mod."github.com/go-openapi/spec"]
    version = "v0.22.2"
    hash = "sha256-o9A6ZVaVPUVP2ssO0I4CDTuGyRuhL/VCM28jU0l32ps="
  [mod."github.com/go-openapi/swag/conv"]
    version = "v0.25.4"
    hash = "sha256-uHgTdZC76LMSsq+x+RyeclnOgBsS0ID2cLgfjzFk0KQ="
  [mod."github.com/go-openapi/swag/jsonname"]
    version = "v0.25.4"
    hash = "sha256-Z6uETeudh8W+/SGxFBnOB/VlJeRPRkFgCyJmntpz7bc="
  [mod."github.com/go-openapi/swag/jsonutils"]
    version = "v0.25.4"
    hash = "sha256-TQGeMImUuL5BWDoBHKAjZ1BvvxPXkFrV3TMgb82IrLk="
  [mod."github.com/go-openapi/swag/loading"]
    version = "v0.25.4"
    hash = "sha256-xr8OnFqB/kwBj3yf9HiLJwDcpL7I3/qJYlKb6VWbVFA="
  [mod."github.com/go-openapi/swag/stringutils"]
    version = "v0.25.4"
    hash = "sha256-rVo5NBH+oLLX9kaemUYWILd+TKw/TDTB8UdSz+mn3m8="
  [mod."github.com/go-openapi/swag/typeutils"]
    version = "v0.25.4"
    hash = "sha256-59RHnK6ugsAUc+A8DZCj7gZ3bJnt01Al7T/1kzM9PpA="
  [mod."github.com/go-openapi/swag/yamlutils"]
    version = "v0.25.4"
    hash = "sha256-zba7QX7Ds05oZq1opP/vwRSBEDaJ1pKm+9DgrsOuR9w="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.29.0"
    hash = "sha256-HFiWBwxNlzoyMlRwA92rAiEGjBy9Dz/ZUKSRp8pXB2Y="
  [mod."github.com/go-shiori/dom"]
    version = "v0.0.0-20230515143342-73569d674e1c"
    hash = "sha256-4lm9KZfR2XnfZU9KTG+4jqLYZqbfL74AMO4y3dKpIbg="
  [mod."github.com/go-shiori/go-readability"]
    version = "v0.0.0-20251205110129-5db1dc9836f0"
    hash = "sha256-oDAW6bUc6W7XeJpw/xeMb8fwD7BZcpN3o/YmJTWwdfs="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.5"
    hash = "sha256-/EtlGihP0/7oInzMC5E0InZ4b5Ad3s4xOpqotloi3xw="
  [mod."github.com/goccy/go-yaml"]
    version = "v1.19.1"
    hash = "sha256-zlT9y4wkvyv7RBv48jdJqOM2lrDMLrC6Z6hCl90c5hQ="
  [mod."github.com/gogs/chardet"]
    version = "v0.0.0-20211120154057-b7413eaefb8f"
    hash = "sha256-4MeqBJsh4U+ZEbfdDwdciTYMlQWkCil2KJbUxHjBSIo="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20241129210726-2c02b8208cf8"
    hash = "sha256-AdLZ3dJLe/yduoNvZiXugZxNfmwJjNQyQGsIdzYzH74="
  [mod."github.com/google/go-cmp"]
    version = "v0.7.0"
    hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM="
  [mod."github.com/google/go-github/v66"]
    version = "v66.0.0"
    hash = "sha256-o4usfbApXwTuwIFMECagJwK2H4UMJbCpdyGdWZ5VUpI="
  [mod."github.com/google/go-querystring"]
    version = "v1.1.0"
    hash = "sha256-itsKgKghuX26czU79cK6C2n+lc27jm5Dw1XbIRgwZJY="
  [mod."github.com/google/s2a-go"]
    version = "v0.1.9"
    hash = "sha256-0AdSpSTso4bATmM/9qamWzKrVtOLDf7afvDhoiT/UpA="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/googleapis/enterprise-certificate-proxy"]
    version = "v0.3.7"
    hash = "sha256-/HrrJAEQs9Ot5hyRY0cdJmg0uxzjuC7IbpntBhTVt8Y="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.15.0"
    hash = "sha256-toGf0MpDZOwR4/naEIpcfi2aDKU0/u/9BT+lX2CmWhM="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/hasura/go-graphql-client"]
    version = "v0.14.4"
    hash = "sha256-TBNYIfC2CI0cVu7aZcHSWc6ZkgdkWSSfoCXqoAJT8jw="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jbenet/go-context"]
    version = "v0.0.0-20150711004518-d14ea06fba99"
    hash = "sha256-VANNCWNNpARH/ILQV9sCQsBWgyL2iFT+4AHZREpxIWE="
  [mod."github.com/jessevdk/go-flags"]
    version = "v1.6.1"
    hash = "sha256-Q5WFTgRxYio0+ay3sbQeBPKeJAFvOdiDVkaTVn3hoTA="
  [mod."github.com/joho/godotenv"]
    version = "v1.5.1"
    hash = "sha256-kA0osKfsc6Kp+nuGTRJyXZZlJt1D/kuEazKMWYCWcQ8="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/kballard/go-shellquote"]
    version = "v0.0.0-20180428030007-95032a82bc51"
    hash = "sha256-AOEdKETBMUC39ln6jBJ9NYdJWp++jV5lSbjNqG3dV+c="
  [mod."github.com/kevinburke/ssh_config"]
    version = "v1.2.0"
    hash = "sha256-Ta7ZOmyX8gG5tzWbY2oES70EJPfI90U7CIJS9EAce0s="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.3.0"
    hash = "sha256-50JhbQyT67BK38HIdJihPtjV7orYp96HknI2VP7A9Yc="
  [mod."github.com/leodido/go-urn"]
    version = "v1.4.0"
    hash = "sha256-Q6kplWkY37Tzy6GOme3Wut40jFK4Izun+ij/BJvcEu0="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.32"
    hash = "sha256-su0SoXnt5pE78t5VXFXQoH2dtP0ohWdyj3TNSZQyWE0="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/nicksnyder/go-i18n/v2"]
    version = "v2.6.0"
    hash = "sha256-UrSECFbpCIg5avJ+f3LkJy/ncZFHa4q8sDqDIQ3YZJM="
  [mod."github.com/ollama/ollama"]
    version = "v0.13.5"
    hash = "sha256-gr8dMdGfyXhEgO22MOmtIZEXlBrOsEecOhi/AmU5D+0="
  [mod."github.com/openai/openai-go"]
    version = "v1.12.0"
    hash = "sha256-JHLlKvDwERPf728GUXBsKU58ODgCxcxEe9TKJTGAG1w="
  [mod."github.com/otiai10/copy"]
    version = "v1.14.1"
    hash = "sha256-8RR7u17SbYg9AeBXVHIv5ZMU+kHmOcx0rLUKyz6YtU0="
  [mod."github.com/otiai10/mint"]
    version = "v1.6.3"
    hash = "sha256-/FT3dYP2+UiW/qe1pxQ7HiS8et4+KHGPIMhc+8mHvzw="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.4"
    hash = "sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q="
  [mod."github.com/pjbgf/sha1cd"]
    version = "v0.4.0"
    hash = "sha256-a+KXfvy1KEna9yJZ+rKXzyTT0A3hg6+yvgqQKD0xXFQ="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/quic-go/qpack"]
    version = "v0.6.0"
    hash = "sha256-xaxHnTKIZt1cHK5ZqTuSTOt5RNSjQB37GlrIgEGBskM="
  [mod."github.com/quic-go/quic-go"]
    version = "v0.57.1"
    hash = "sha256-MdXc0GRVp3YuN9XFoGFOjgIcIMp7yoLqwfEikZp1i4w="
  [mod."github.com/samber/lo"]
    version = "v1.52.0"
    hash = "sha256-xgMsPJv3rydHH10NZU8wz/DhK2VbbR8ymivOg1ChTp0="
  [mod."github.com/sergi/go-diff"]
    version = "v1.4.0"
    hash = "sha256-rs9NKpv/qcQEMRg7CmxGdP4HGuFdBxlpWf9LbA9wS4k="
  [mod."github.com/sgaunet/perplexity-go/v2"]
    version = "v2.14.0"
    hash = "sha256-yyuvp7vB4OSE9OfIsqj0TavR+synNlLQKZVT872GZnM="
  [mod."github.com/skeema/knownhosts"]
    version = "v1.3.1"
    hash = "sha256-kjqQDzuncQNTuOYegqVZExwuOt/Z73m2ST7NZFEKixI="
  [mod."github.com/spf13/cobra"]
    version = "v1.10.2"
    hash = "sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.9"
    hash = "sha256-YAjyYpq5BXCosVJtvYLWFG1t4gma2ylzc7ILLoj/hD8="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/swaggo/files"]
    version = "v1.0.1"
    hash = "sha256-bNBmpJaM7g1BNwd7VxNIRSdY35NKSXhYHGfnZsSEUZ8="
  [mod."github.com/swaggo/gin-swagger"]
    version = "v1.6.1"
    hash = "sha256-9TQuEmPpDO2QL0c9VwjK9uwB1jka08Ox6fje2RwVpUc="
  [mod."github.com/swaggo/swag"]
    version = "v1.16.6"
    hash = "sha256-na5+ZylxPFKoMJcgx8nmSJXMMkKFCyuh1qSkb7Qth/I="
  [mod."github.com/tidwall/gjson"]
    version = "v1.18.0"
    hash = "sha256-CO6hqDu8Y58Po6A01e5iTpwiUBQ5khUZsw7czaJHw0I="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.1"
    hash = "sha256-S0uTDDGD8qr415Ut7QinyXljCp0TkL4zOIrlJ+9OMl8="
  [mod."github.com/tidwall/sjson"]
    version = "v1.2.5"
    hash = "sha256-OYGNolkmL7E1Qs2qrQ3IVpQp5gkcHNU/AB/z2O+Myps="
  [mod."github.com/twitchyliquid64/golang-asm"]
    version = "v0.15.1"
    hash = "sha256-HLk6oUe7EoITrNvP0y8D6BtIgIcmDZYtb/xl/dufIoY="
  [mod."github.com/ugorji/go/codec"]
    version = "v1.3.1"
    hash = "sha256-VQtXVaKxXjm5Q60hCgVKZxNywl6SJFPqju6JNjADp4w="
  [mod."github.com/xanzy/ssh-agent"]
    version = "v0.3.3"
    hash = "sha256-l3pGB6IdzcPA/HLk93sSN6NM2pKPy+bVOoacR5RC2+c="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.2.1"
    hash = "sha256-73bFYhnxNf4SfeQ52ebnwOWywdQbqc9lWawCcSgofvE="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.61.0"
    hash = "sha256-4pfXD7ErXhexSynXiEEQSAkWoPwHd7PEDE3M1Zi5gLM="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.38.0"
    hash = "sha256-OU4EVEGwbopbYZLDBfAelR/4yjzfV+UVp4UFt3UvkOE="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.38.0"
    hash = "sha256-5W6Yd9nl/eyvL29e9hSfosISpxfSQcBAwkqI4htHWCg="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.38.0"
    hash = "sha256-gNXUPmsPAw6JVH3YT/xwmRpn5QoDxyzc9kLe/5ldo0o="
  [mod."go.uber.org/mock"]
    version = "v0.6.0"
    hash = "sha256-m11cxIbrvOowa6xj11AztzfFk86DwR6SNO1lStcKzvo="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.4"
    hash = "sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4="
  [mod."golang.org/x/arch"]
    version = "v0.23.0"
    hash = "sha256-ynvhsw8ZYgKTzFn1wnIj3/p+1O/Ty5PX1Lnj+NMTAQQ="
  [mod."golang.org/x/crypto"]
    version = "v0.46.0"
    hash = "sha256-I8N/spcw3/h0DFA+V1WK38HctckWIB9ep93DEVCALxU="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20250531010427-b6e5de432a8b"
    hash = "sha256-QaFfjyB+pogCkUkJskR9xnXwkCOU828XJRrzwwLm6Ms="
  [mod."golang.org/x/mod"]
    version = "v0.31.0"
    hash = "sha256-ZVNmaZADgM3+30q9rW8q4gP6ySkT7r1eb4vrHIlpCjM="
  [mod."golang.org/x/net"]
    version = "v0.48.0"
    hash = "sha256-oZpddsiJwWCH3Aipa+XXpy7G/xHY5fEagUSok7T0bXE="
  [mod."golang.org/x/oauth2"]
    version = "v0.34.0"
    hash = "sha256-5eqpGGxJ7FJsPmfRek6roeGmkWHBMJaWYXyz8gXJsS4="
  [mod."golang.org/x/sync"]
    version = "v0.19.0"
    hash = "sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno="
  [mod."golang.org/x/sys"]
    version = "v0.39.0"
    hash = "sha256-dxTBu/JAWUkPbjFIXXRFdhQWyn+YyEpIC+tWqGo0Y6U="
  [mod."golang.org/x/text"]
    version = "v0.32.0"
    hash = "sha256-9PXtWBKKY9rG4AgjSP4N+I1DhepXhy8SF/vWSIDIoWs="
  [mod."golang.org/x/tools"]
    version = "v0.40.0"
    hash = "sha256-ksmhTnH9btXKiRbbE0KGh02nbeNqNBQKcfwvx9dE7t0="
  [mod."google.golang.org/api"]
    version = "v0.258.0"
    hash = "sha256-hxwJz4Vzh87Bc49QCndKrO+34wfzF1ORGMeF5kmk22Q="
  [mod."google.golang.org/genai"]
    version = "v1.40.0"
    hash = "sha256-J/jDKYz2gU01AvwmFTnXUTv5HwnZbZ+nem+g0B6PdEg="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20251213004720-97cd9d5aeac2"
    hash = "sha256-I3ZNpNjKKvTq4DVNw3wLKrCuORabZ0oYj0KKhOMI/MA="
  [mod."google.golang.org/grpc"]
    version = "v1.78.0"
    hash = "sha256-oKsu3+Eae5tpFOZ9K2ZzYh1FgdYdEnEIB1C+UIxSD+E="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.11"
    hash = "sha256-7W+6jntfI/awWL3JP6yQedxqP5S9o3XvPgJ2XxxsIeE="
  [mod."gopkg.in/warnings.v0"]
    version = "v0.1.2"
    hash = "sha256-ATVL9yEmgYbkJ1DkltDGRn/auGAjqGOfjQyBYyUo8s8="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
